"""empty message

Revision ID: 7f6dd84436ef
Revises: None
Create Date: 2016-02-07 04:28:22.227656

"""

# revision identifiers, used by Alembic.
revision = '7f6dd84436ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closet_name'), 'closet', ['name'], unique=True)
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_name'), 'hero', ['name'], unique=True)
    op.create_table('skeleton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skeleton_name'), 'skeleton', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skeleton_name'), table_name='skeleton')
    op.drop_table('skeleton')
    op.drop_index(op.f('ix_hero_name'), table_name='hero')
    op.drop_table('hero')
    op.drop_index(op.f('ix_closet_name'), table_name='closet')
    op.drop_table('closet')
    ### end Alembic commands ###
